### PR TITLE
adding dataXoffset and dataYoffset

### PR DESCRIPTION
**Pull request by fuddl**
I'd like to _walk around_ within my scene. Now I could update the xyz coordinate of every object manually, but there is already a `dataZoffset` variable that only lets me move every item on the Z axis. Why isn't there a corresponding offset variable for the other two coordinates?

Let me know what you think 🙂

### CODE REVIEW

**Comment by mithi** [comment]
Hey this looks pretty awesome! I'll review this as soon as I can.

**Comment by fuddl** [comment]
I figured out that I should rather use `camTx`, `camTy` and `camTz` for that 😅

**Comment by fuddl** [comment]
nah, it turns out offsetting the data has a different effect than translating the camera (one might say I should be familiar to three dimensionality at this stage of my life 😅). I would at least ask, why it is only the z axis that can be offset.

**Comment by mithi** [comment]
> nah, it turns out offsetting the data has a different effect than translating the camera (one might say I should be familiar to three dimensionality at this stage of my life 😅). I would at least ask, why it is only the z axis that can be offset.

I didn't need them at that time 😅. I use `dataZoffset` because I wanted to control how the rotation (in the x, y, z axes) worked with respect to the data 😄

**Comment by mithi** [comment]
> I'd like to _walk around_ within my scene. Now I could update the xyz coordinate of every object manually, but there is already a `dataZoffset` variable that only lets me move every item on the Z axis. Why isn't there a corresponding offset variable for the other two coordinates?
> 
> Let me know what you think 🙂

Hey, you didn't give me permission to edit your pull request. Please allow maintainers to edit your pull request! Thanks!

```
➜  bare-minimum-3d git:(feat/PR-023) git push PR-023 feat/PR-023 --force
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 14.83 KiB | 1.24 MiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
To https://github.com/fuddl/bare-minimum-3d.git
 ! [remote rejected] feat/PR-023 -> feat/PR-023 (permission denied)
error: failed to push some refs to 'https://github.com/fuddl/bare-minimum-3d.git'
```

**Comment by fuddl** [comment]
Yes, of course. I apologize

**Comment by mithi** [comment]
> Yes, of course. 

Awesome! 😃

**Pull request merged**
